### Test Login Endpoint
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "username": "ron",
  "password": "123"
}

### Test Register Endpoint
POST http://127.0.0.1:8000/api/users/register/
Content-Type: application/json

{
  "username": "ron2",
  "email": "ron@example.com",
  "password": "roncada123",
  "confirm_password": "roncada123",
  "first_name": "Ron",
  "last_name": "Ae"
}

### Test registered User to login
POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "username": "ron2",
  "password": "roncada123"
}

### Test Categories - List all categories
GET http://127.0.0.1:8000/api/notes/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMzQ1OTA1LCJpYXQiOjE3NTMzNDU2MDUsImp0aSI6IjhiOTc3NGQ1Y2JjZjQwYWQ5NzBlMThiN2EwN2QwOGU2IiwidXNlcl9pZCI6Mn0.PuG9HSGFo82CedRmEg3Bx_NzAdgPDuqMwapjajtmK5w

### Test Categories - Create a new category
POST http://127.0.0.1:8000/api/notes/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMzQ1OTA1LCJpYXQiOjE3NTMzNDU2MDUsImp0aSI6IjhiOTc3NGQ1Y2JjZjQwYWQ5NzBlMThiN2EwN2QwOGU2IiwidXNlcl9pZCI6Mn0.PuG9HSGFo82CedRmEg3Bx_NzAdgPDuqMwapjajtmK5w

{
  "name": "New Category",
  "description": "Description for new category"
}


### Test Notes - List all notes
GET http://127.0.0.1:8000/api/notes/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMzQ3MDkyLCJpYXQiOjE3NTMzNDY3OTIsImp0aSI6IjAzNDJkMDBkZjlmZTQwMDdhZGZkOWQ1ZDUyMmQ1YzdkIiwidXNlcl9pZCI6Mn0.lsWc_8Z0apTydiDzJmO2lP73tlFgebldFPPlKt44LGo

### Test Notes - Create a new note
POST http://127.0.0.1:8000/api/notes/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMzQ3MDkyLCJpYXQiOjE3NTMzNDY3OTIsImp0aSI6IjAzNDJkMDBkZjlmZTQwMDdhZGZkOWQ1ZDUyMmQ1YzdkIiwidXNlcl9pZCI6Mn0.lsWc_8Z0apTydiDzJmO2lP73tlFgebldFPPlKt44LGo

{
  "title": "New Note",
  "content": "Content for the new note"
}